services:
  # This service is used to build the Docker image
  # The docker image is built from the root directory
  aio:
    image: ai_olympics
    container_name: aio_dev
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
      - TERM=xterm-256color
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    volumes:
        # These volumes allow X11 Forwarding
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /tmp/.docker.xauth
        target: /tmp/.docker.xauth
        # This overlay allows changes on the local files to
        # be reflected within the container immediately
      - type: bind
        source: ../
        target: /home/ubuntu/double_pendulum
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true
